xcodeproj 'RatesNetworkApi.xcodeproj'
platform :ios, '8.0'
inhibit_all_warnings!

pod 'Mantle', '~> 2.0.0'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'CocoaLumberjack', '~> 1.9'
pod 'Nocilla', '~> 0.9.0'
pod 'AFNetworking', '~> 2.5.3'
pod 'AFNetworkActivityLogger', '~> 2.0.4'

target :RatesNetworkApiTests, :exclusive => true do
    pod 'Expecta', '~> 0.4.2'
    link_with :RatesNetworkApi
end

